global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: ''
    scrape_interval: 5s
    static_configs:
      - targets: ['ip_node_exporter:9100']
    basic_auth:
      username: "username_node_exporter"
      password: "password_node_exporter"
    scheme: http
